// Generates the theme CSS files (--lp-* custom properties) from a Theme object.
// Run: pnpm --filter @loupe/tokens generate
// Both generated files are checked in; regenerate whenever a theme changes.
// NOTE: node:fs / node:url are imported lazily in the CLI block below so this
// module (re-exported by the @loupe/tokens barrel) stays browser-importable.
import { modern } from './theme-modern.ts';
import type { Theme } from './theme.ts';
import { tokens } from './tokens.ts';

const kebab = (s: string): string => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/** Every theme emits the same var NAMES; only the values differ. */
export function generateCss(theme: Theme = tokens, label = 'classic'): string {
  const vars: Array<[string, string]> = [];
  const add = (name: string, value: string | number) => {
    vars.push([`--lp-${name}`, String(value)]);
  };

  const { color, font } = theme;
  for (const [k, v] of Object.entries(color.bg)) add(`bg-${kebab(k)}`, v);
  add('scrim', color.scrim);
  for (const [k, v] of Object.entries(color.border)) add(`border-${kebab(k)}`, v);
  for (const [k, v] of Object.entries(color.text)) add(`text-${kebab(k)}`, v);
  for (const [toneName, triad] of Object.entries(color.tone)) {
    for (const [part, v] of Object.entries(triad)) add(`tone-${kebab(toneName)}-${part}`, v);
  }
  for (const [k, v] of Object.entries(color.accent)) add(`accent-${kebab(k)}`, v);
  for (const [k, v] of Object.entries(color.diff)) add(`diff-${kebab(k)}`, v);
  for (const [k, v] of Object.entries(color.claim)) add(`claim-${kebab(k)}`, v);

  add('font-family', font.family);
  add('font-mono', font.familyMono);
  for (const [k, v] of Object.entries(font.weights)) add(`font-weight-${kebab(k)}`, v);
  add('font-weight-default', font.defaultWeight);
  // Semantic weights — what components actually ask for.
  for (const [k, v] of Object.entries(font.weight)) add(`weight-${kebab(k)}`, v);
  add('letter-spacing', font.letterSpacing);
  add('font-size-base', `${font.baseSize}px`);
  add('line-height-base', font.baseLineHeight);
  // Scale NAMES are frozen; the theme chooses the pixels behind each name.
  for (const size of font.scale) add(`size-${size}`, `${font.sizePx[size]}px`);
  for (const [k, v] of Object.entries(font.tracking)) add(`tracking-${kebab(k)}`, v);
  add('prose-max-ch', `${font.prose.maxCh}ch`);
  add('prose-line-height', font.prose.lineHeight);
  add('diff-line-height', font.diffLineHeight);

  add('radius', theme.radius);
  for (const [k, v] of Object.entries(theme.radii)) add(`radius-${kebab(k)}`, v);
  add('shadow', theme.shadow);
  for (const [k, v] of Object.entries(theme.shadows)) add(`shadow-${kebab(k)}`, v);
  for (const [k, v] of Object.entries(theme.transform)) add(`transform-${kebab(k)}`, v);
  for (const [k, v] of Object.entries(theme.badge)) add(`badge-${kebab(k)}`, v);
  add('accent-width-atom', `${theme.accentWidth.atom}px`);
  add('accent-width-structural', `${theme.accentWidth.structural}px`);
  for (const [k, v] of Object.entries(theme.spacing)) add(`space-${kebab(k)}`, `${v}px`);

  const body = vars.map(([n, v]) => `  ${n}:${v};`).join('\n');
  return `/* generated by @loupe/tokens (src/generate-css.ts) — do not edit by hand */\n/* theme: ${label} */\n:root {\n${body}\n}\n`;
}

/** filename -> (theme, label). The CLI writes every entry. */
export const THEME_FILES: Array<{ file: string; theme: Theme; label: string }> = [
  { file: 'theme-classic.css', theme: tokens, label: 'classic' },
  { file: 'theme-modern.css', theme: modern, label: 'modern' },
];

if (typeof process !== 'undefined' && process.argv?.[1] !== undefined) {
  void (async () => {
    const { fileURLToPath } = await import('node:url');
    if (fileURLToPath(import.meta.url) !== process.argv[1]) return;
    const { writeFileSync } = await import('node:fs');
    for (const { file, theme, label } of THEME_FILES) {
      const out = fileURLToPath(new URL(`../${file}`, import.meta.url));
      writeFileSync(out, generateCss(theme, label));
      console.log(`wrote ${out}`);
    }
  })();
}
